---
version: v1.0
app_port: 4000
auth_scheme: couchdb
initial_admin: admin
configtxlator_url_original: http://localhost:7059
host_url: http://localhost:4002
default_user_password_initial: password
cookie_name: com.ibm.cloud.console.blockchain.optools.dev
